version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/proyecto-docker
    environment:
      - DEBUG=1
    command: python3 myproject/manage.py runserver 0.0.0.0:8000